### ISSUE TITLE
Data used in demos and notebooks is different than the provided data

### ISSUE THREAD

**Issue by onahman** [qiaochen/TranSpaAnalysis#1]
Hi,
I would like to use your package for imputation of Visium data.
However, I find it difficult to understand what are the exact inputs to your method.
I tried to understand it myself from the notebooks, but they use .pkl files (that seem to be a combination of raw data and processed data). I downloaded the data from the link you provided and there are no .pkl files in there. Only raw data I assume.
Would you be able to provide the .pkl file or an explanation of what are the exact inputs? For example, am I training and testing on the same sample (but split it)?
Thank you for this tool and for your help.

**Comment by qiaochen** [comment]
Hi onahman,

Many thanks for your feedback.

The function signature of the basic lowrank mode (TransImpLR) is 
```python
expTransImp(
    df_ref=raw_scrna_df,
    df_tgt=raw_spatial_df,
    train_gene=train_gene,
    test_gene=test_gene,
    signature_mode='cell',
    mapping_mode='lowrank',
    n_epochs=2000,
    seed=seed,
    device=device
 )
```
here data relevant params are:
- `df_ref` would be a reference expression pandas DataFrame,  each row is a cell and each column a gene
-  `df_tgt` is a ST expression pandas DataFrame with the same structure,
-  `train_gene` would be the list of shared genes used for training the model
-  `test_gene` would be the list of genes to be imputed in ST space, the genes should be in the reference DataFrame

The preprocessed `.pkl` files are included in [zenodo](https://zenodo.org/record/8214466), since they are intermediate outputs, I included them in `output.tar.gz`. After downloading and extracting the files, in the folder `output/preprocessed_dataset/` are those `XXX.pkl` files.


If you downloaded `data.tar.gz`, you can also run the preprocess scripts (e.g.,[`preprocess_mouseliver.py`](https://github.com/qiaochen/TranSpaAnalysis/blob/main/preprocess_mouseliver.py)) to obtain `pkl` files.

Hope it helps!

Best
